### ISSUE TITLE
Cannot filter tabs with multiple terms

### ISSUE THREAD

**Issue by piroor** [NiklasGollenstede/tst-search#10]
# Steps to reproduce

1. Start Firefox 89.0 (64bit) on Windows 10 21H1.
2. Install Tree Style Tab 3.8.2 from https://addons.mozilla.org/firefox/addon/tree-style-tab/ .
3. Install TST Tab Search 0.0.3 from https://addons.mozilla.org/firefox/addon/tst-search/ .
4. Prepare 4 tabs:
   - https://addons.mozilla.org/firefox/addon/tree-style-tab/
   - https://addons.mozilla.org/firefox/addon/tst-search/
   - about:addons
   - about:newtab
5. Input a search query "tab tree" to the search field provided by TST Tab Search.

# Expected result

The tab https://addons.mozilla.org/firefox/addon/tree-style-tab/ is highlighted as a matched tab.

# Actual result

All tabs are shrunken and there is no matched tab.

**Comment by piroor** [comment]
Recently I tried similar feature, and I implemented a code to generate a regular expression from multiple terms:
https://gitlab.com/clear-code/tb-corporative-contacts/-/blob/master/common/ItemsSearcher.js#L103-143
It generates a regular expression like `/(tab|tree|ja).*(?!\1)(tab|tree|ja).*(?!\1|\2)(tab|tree|ja)/i` from an input `tab tree ja`, it matches to any text containing these three terms in any order. Moreover, it also supports generation of a rejector regexp with words starting with `-`. For example, if you give terms `tab tree -ja -https`, it generates two regexps:

* `/(tab|tree).*(?!\1)(tab|tree)/i` (matcher)
* `/(ja|https).*(?!\1)(ja|https)/i` (rejector)

So, `tabs.filter(tab => matcher.test(tab.title + ' ' + tab.url) && !rejector.test(tab.title + ' ' + tab.url))` will extract tabs containing words "tab" and "tree" but never containing "ja" and "https".

**Comment by piroor** [comment]
FYI: The technique is based on the negative look-ahead assertion.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions#other_assertions

**Comment by NiklasGollenstede** [comment]
Yes. It currently does a full test search, as in, with some modifications based on the selected flags, it looks for a literal string matching.

That said, in a scenario with (too) may tabs, where one doesn't quite know what one is even searching for, a keyword search more similar to a search engine, could be good.

I'll look into this, esp. also the run time of any regular expressions (or other search mechanism).
Might want to limit the size of the search term (mostly in case of accidentally pasting long texts there) ...

**Comment by NiklasGollenstede** [comment]
So, yeah. As soon as I saw the regular expressions in the second post I though that that might not perform well.

Pretty much any regexp that has more than one (unbounded) repetition (e.g. `*`) of the same thing (esp. `.`) on one matching "path", you run risk of ["catastrophic" backtracking](https://www.regular-expressions.info/catastrophic.html).
Often, this is especially noticeable for non-matching strings.

Depending one the engine, making the repetition non-greedy (`*` => `*?`) improves things a bit, and the ungreedy behavior is usually what people expect how `*` behaves, but it doesn't really solve the issue.

Also, the size of your regexp grows quadratically with the number of terms to match.

So I searched for "regexp and" and found an [approach[(https://stackoverflow.com/a/470602) to optimize this:
* put the words in positive lookaheads
* prefix with `.*?` to match the words anywhere
* anchor at start (to avoid re-trying to match on non-matching strings
* use negative lookaheads for negations

So your example `tab tree -ja -https` becomes `/^(?=.*?tab)(?=.*?tree)(?!.*?ja)(?1.*?https)/`.

For testing, I created a 6 term expression using your [original pattern](https://regex101.com/r/PCAWPK/1) and the [new pattern](https://regex101.com/r/hfUiYL/1).
RegEx101 shows 42.000 vs 1.500 debugging steps (on the same subject string).
Regular expression engines do work differently and have different characteristics in terms of run time and state size. So this may not be an *accurate* reflection of the actual behavior, but it should give an idea.

Side remark: in https://gitlab.com/clear-code/tb-corporative-contacts/-/blob/master/common/ItemsSearcher.js#L104 you require a user entered RegExps not to contain `\`. Is that intentional?

---

As for the actual issue you raised with TST, I am not sure how to handle this yet. There are already a bunch of options, and one might expect this to work across multiple tab properties (`title`, `url`).

**Comment by piroor** [comment]
Thank you for advice, I didn't know the smarter way! I'm ashamed of my ignorance, I stupidly cited the negative lookahead based method from an article I found at first. And as you remarked I wrongly excepted the "/" character from regexp shorthand pattern. I've updated the ItemSearcher implementation with both changes.

> As for the actual issue you raised with TST, I am not sure how to handle this yet. There are already a bunch of options, and one might expect this to work across multiple tab properties (title, url).

Just an idea, how about this?:

```javascript
function toSearchString(tab) {
  return [
    '',
    `title:${tab.title}`,
    `url:${tab.url}`,
    // and more properties...
  ].join('\n');
}

function toMatcher(query) {
  return new RegExp(
    '^' + query.trim().split(/\s+/).map(term => {
      const matched = term.match(/^(title|url|<and more properties...>):(.+)$/);
      if (matched)
        return `(?=[\\s\\S]*\\n${matched[1]}:.*${matched[2]})`;
      else
        return `(?=[\\s\\S]*\\n[^:]+:.*${term})`;
    }).join('')
  );
}

const tab1 = {
  title: 'foobar',
  url: 'https://example.org/'
};
const tab2 = {
  title: 'foobar',
  url: 'https://example.org/bar/'
};

// search across properties
console.log(toMatcher('foo bar').test(toSearchString(tab1))); // true
console.log(toMatcher('foo bar').test(toSearchString(tab2))); // true

// search in specific property
console.log(toMatcher('title:foo url:bar').test(toSearchString(tab1))); // false
console.log(toMatcher('title:bar url:foo').test(toSearchString(tab2))); // false
console.log(toMatcher('title:foo url:bar').test(toSearchString(tab2))); // true
```

I sometimes use such (maybe) slow matchers and combine it with progressive operations like the ItemSearchar.

**Comment by NiklasGollenstede** [comment]
Closing this, as the keyword search works sufficiently well and addresses the original issue.
