### ISSUE TITLE
Mispositioning of container marker of pinned tabs

### ISSUE THREAD

**Issue by piroor** [NiklasGollenstede/tst-search#14]
[This CSS declaration](https://github.com/NiklasGollenstede/tst-search/blob/dfabeb77c15d39fd9a14c5860414c6b1d39160ce/src/background/index.esm.js#L48) overrides [special style declarations for pinned tabs](https://github.com/piroor/treestyletab/blob/1071ada8a1c52c1dc92ecbb5b48230e1c56a2d35/webextensions/sidebar/styles/base.css#L725), as the result the container marker is mis-positioned as the following screenshot:

![image](https://user-images.githubusercontent.com/70062/141249522-69659cd8-f2f0-47a2-bdac-9ac84231da50.png)

In this screenshot the orange bar's right edge is unexpectedly expanded.

Expected:
![image](https://user-images.githubusercontent.com/70062/141250124-e84bf7e8-bfa0-43b3-858e-d80021f5866c.png)

* Firefox 94.0.1 on Windows 10
* TST 3.8.15
* TST Search 0.0.4

**Comment by NiklasGollenstede** [comment]
Upsi. I am actually using pinned container tabs, but didn't notice ...
Messing with TST's CSS is definitely tricky, especially those parts which are permanently active.

**Comment by piroor** [comment]
Is there any further task I should do about this on TST side?

**Comment by NiklasGollenstede** [comment]
I think this works fine in the latest dev build, no? I would "release" this once there is more than a tiny CSS fix to publish.

Maybe a related thing (that I didn't care enough about to fix it -- not saying you need to, but maybe there is a workaround):
With the "Show tab IDs while searching" TST Search option, the tab IDs are inserted as an `::after` element of the `.tab`, because that can use `content: attr(data-tab-id)`. Really it should probably be inside the `tab-item-substance`, especially it should be to the center of the `.contextual-identity-marker`. Visually, that can be achieved by setting `tab-item-substance { position: static; }`, but that breaks the placement of the `:hover` border marker on the other side.
(all that is with the Photon theme.)

**Comment by piroor** [comment]
Oh, thanks, I just worried that something my mistake blocked your release (because I sometimes misunderstand replies to me.)

There is no positive reason I didn't set `tab-id` to other elements, so I've introduced a change https://github.com/piroor/treestyletab/commit/39119b4f42eb3a4e516d08beab4dc20f7778201c to TST. Now `<tab-item-substance>`, `<tab-label>` and `<span class="label-content">` inherit `data-tab-id` and `data-window-id` from `<tab-item>`. I hope it helps customization with `attr()`.
