### ISSUE TITLE
White ugly border around box since Firefox 102

### ISSUE THREAD

**Issue by NewsGuyTor** [NiklasGollenstede/tst-search#22]
This appeared recently, after Firefox updated:
<img width="271" alt="Skjermbilde 2022-06-10 kl  13 42 40" src="https://user-images.githubusercontent.com/19603024/173084269-fda38b17-085e-4d53-96dc-f7ea9b55b106.png">

Previously, it had the same background colors as the tabs seen above. 

I'm using Firefox Developer Edition, with the Developer Edition theme and the Photon TST theme.

**Comment by D1g1K1d** [comment]
same. is this something that can be fixes using TST's CSS styling, and if so what is the element/property name to use?
if not, is this something that can be corrected on the developer end? thank you so much for a great plugin and for your help!

**Comment by KrisSchneider** [comment]
Is there a CSS code we can use to fix this issue?

**Comment by NiklasGollenstede** [comment]
The panel used to have a transparent background. Then TST changed something about how it embeds the panel, putting a white background behind it (I am 90% sure this has nothing to do with Firefox, so fixing it within TST should be possible).

Since TST didn't revert this, I now gave the panel a solid background, in a color that happens to match my theme (and some other color for the light theme). I hope that color also works reasonably well for other themes. If not, i guess one would need to nag piroor about this (but I won't do that).

**Comment by KrisSchneider** [comment]
Thank you for fixing this issue. The search function looks much better now.
![(firefox)h6L240_07-29-2022](https://user-images.githubusercontent.com/101912712/181841063-02ec27a7-1b49-4640-a433-b8f7ec33333e.jpg)
