### ISSUE TITLE
Missing from Firefox Add-Ons directory

### ISSUE THREAD

**Issue by patrickbdev** [NiklasGollenstede/tst-search#8]
Is this meant to be available on the Firefox Add-Ons directory as it isn't listed.
If not, are there instructions on how to install the release build?

**Comment by Gitoffthelawn** [comment]
I can confirm that it does not appear to be on AMO, or if it is, it is very hard to find there!

I actually was going to add the link to AMO in the README for you, but I couldn't find the extension on AMO either.

**Comment by NiklasGollenstede** [comment]
TST Tab Search is indeed not listed on AMO yet.

Releasing this before TST 3.8.0 didn't make  much sense, and once that was released, I made significant changes to the search, which I wanted to test thoroughly before listing this. Since I don't search my tabs thaaat often, I haven't done too much testing yet either.
Also, a proper listing will require some more screenshots/descriptions/etc, which I yet need to create/write.

That said though, except for visibility, there would not be that much changing with a listed version. The listed version will be identical with the DEV build at that point, it just won't be updated quite as often/freely.

But TST Tab Search should really at worst never do more than break itself. It does not change tabs permanently, only how TST shows them.

For now, just get the DEV build, and I'll list this, probably next weekend.

---

> are there instructions on how to install the release build?

I guess I could be more explicit about that:
To install them, go to [releases](https://github.com/NiklasGollenstede/tst-search/releases), under `Latest release` > "Assets" click `*-an.fx.xpi`, click allow and install; they will then update automatically.

**Comment by NiklasGollenstede** [comment]
So last weekend (ffd8c91), after implementing a couple more features, mostly some improvements on how the result highlight styles are put together, and some general cleanup, I finally got around to updating the README, taking a few proper screenshots, and then uploading it [on AMO](https://addons.mozilla.org/en-US/firefox/addon/tst-search/)! Yay.

Thanks for your patience, and happy tab searching!

**Comment by Gitoffthelawn** [comment]
Great job!  I saw it there moments after it was released!  Congrats!

**Comment by patrickbdev** [comment]
You are amazing, I appreciate it! 🙏🙏🙏
